[tool.black]
exclude = '\.eggs|\.git|\.mypy_cache|\.tox|\.venv|_build|buck-out|dist'
line-length = 100
skip-string-normalization = true
target-version = ["py311"]

[tool.isort]
combine_as_imports = true
force_sort_within_sections = true
line_length = 100
profile = "black"

# Require all Python code to be typed by default.
[tool.mypy]
disallow_untyped_defs = true

# Allow untyped definitions for test code.
[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

# These third-party libraries don't expose type information,
# so we tell mypy not to try to type-check our usage of them.
[[tool.mypy.overrides]]
module = ['cv2.*', 'desmume.*', 'ndspy.*', 'zed.*']
ignore_missing_imports = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
