[tool.black]
exclude='\.eggs|\.git|\.mypy_cache|\.tox|\.venv|_build|buck-out|dist'
line-length = 100
skip-string-normalization = true
target-version = ["py39", "py310"]

[tool.isort]
combine_as_imports = true
force_sort_within_sections = true
line_length = 100
profile = "black"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
