$schema: "./settings_schema.json"
settings:
  - name: DigSpots
    flag: true
    supported: false
    description:
      Include shovel dig spots in location pool for randomized items.

  - name: SalvageArmTreasures
    description: Include salvage arm treasures in location pool for randomized items.
    flag: true

  - name: ShopItems
    flag: true
    supported: false
    description:
      Include island shops and Beedle shops in location pool for randomized
      items.

  - name: TreeDrops
    flag: true
    supported: false
    default: true
    description:
      Include tree drops in location pool for randomized items

  - name: DungeonRewardMode
    options:
      - shuffle_amongst_themselves
      - shuffle_with_rest_of_items
    description:
      Whether dungeon rewards should be randomized only amongst themselves,
      or in the general item pool.

  - name: MercayBridgeRepairedFromStart
    flag: true
    description:
      Whether or not the bridge on Mercay is repaired at the start of the
      game.

  - name: HammerClip
    flag: true

  - name: BoomerangClip
    flag: true

  - name: HammerReach
    flag: true
    default: false
    description:
      Require abusing rolling, etc to shift camera for hammer use.

  - name: NoPuzzleSolution
    flag: true
    description:
      For puzzles, don't logically require that player has access to corresponding
      hints.

  - name: MirroredArenaDoors
    flag: true
    supported: false
    description:
      "TODO: write this description"

  - name: SwordMode
    options:
      - start_with_sword
      - randomized_sword
      - swordless
    default: start_with_sword
    supported: false

  - name: PhantomHourglassMode
    options:
      - start_with_phantom_hourglass
      - vanilla_location_phantom_hourglass
      - randomized_phantom_hourglass
    default: start_with_phantom_hourglass
    supported: false
    description:
      Whether to start with the Phantom Hourglass, place it in its "vanilla" location
      in the Temple of the Ocean King, or to randomize it alongside the rest of
      the items.
