# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get the CI tool
        uses: robinraju/release-downloader@v1
        with:
          repository: Ibot02/tmcr-newlogic-ci
          tag: "v1.0"
          filename: "tmcr-newlogic-ci"
          tarBall: false
          zipBall: false

      - name: Make it executable
        run: chmod +x "$GITHUB_WORKSPACE/tmcr-newlogic-ci"

      - name: Run the CI tool
        run: |
          shopt -s globstar
          for file in **/*.logic; do
            ./tmcr-newlogic-ci "$file"
          done;

  test-shuffler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout rando-shuffler repo
        uses: actions/checkout@v2
        with:
          repository: 21aslade/rando-shuffler
          ref: c03c5f4a9190312ee1d9db503806084495f47423
          path: rando-shuffler

      - name: Compile rando-shuffler
        run: cargo build
        working-directory: rando-shuffler
        env:
          CARGO_TERM_COLOR: always

      - name: Make it executable
        run: chmod +x rando-shuffler/target/debug/rando_shuffler

      - name: Run the shuffler
        run: |
          shopt -s globstar
          rm -f rando-shuffler/*.logic  # remove test files
          failed=0;
          for file in **/*.logic; do
            echo "$file... ";
            status=0
            cat "$file" | rando-shuffler/target/debug/rando_shuffler || status=1
            if [[ $status != 0 ]]; then
              failed=1;
            else
              echo " PASSED";
            fi
            echo "-------------------------------"
            echo ""
          done;
          if [[ $failed != 0 ]]; then
            exit 1;
          fi

