name: test
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run tox
        run: |
          pip install tox
          tox

      - name: Lint C code
        run: |
          docker run -w /app -v ${PWD}/base:/app $(docker build -q base/) sh -c "make lint"
