name: test
on:
  push:
jobs:
  lint-type-check:
    name: Lint and type check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Run tox
        run: |
          pip install tox
          tox

  generate-base-patch:
    name: Run patching toolchain and create base patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Fetch PH rom
        run: |
          pip install gdown
          gdown ${{ secrets.PH_GOOGLE_DRIVE_ID }}
        working-directory: base

      - name: Get filename of rom
        id: rom-filename
        shell: bash
        run: |
          echo "::set-output name=filename::$(ls *.nds)"
        working-directory: base

      - name: Get current commit hash
        id: commit-hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        id: buildx        
        uses: docker/setup-buildx-action@v1

      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          context: base/
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PH_ROM_PATH=${{ steps.rom-filename.outputs.filename }}
            VERSION_STRING=${{ steps.commit-hash.outputs.hash }}
          outputs: |
            base/out

      - name: Clone Flips repo
        uses: actions/checkout@v3
        with:
          repository: Alcaro/Flips
          path: base/Flips

      - name: Get latest commit hash from Flips repo
        id: flips-hash
        shell: bash
        run: |
          echo "::set-output name=flips_hash::$(git rev-parse --short HEAD)"
        working-directory: base/Flips

      - name: Cache Flips executable
        uses: actions/cache@v2
        id: flips-cache
        env:
          cache-name: cache-flips
        with:
          path: base/Flips/*
          key: ${{ env.cache-name }}-${{ steps.flips-hash.outputs.flips_hash }}-${{ runner.os }}

      - name: Compile Flips tool
        if: steps.flips-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install g++ build-essential
          chmod +x ./make.sh
          ./make.sh
        working-directory: base/Flips

      - name: Create patch
        run: |
          chmod +x ./Flips/flips
          ./Flips/flips --create $(ls *.nds) out/out.nds patch.bps
        working-directory: base

      - uses: actions/upload-artifact@v3
        with:
          name: patch.bps
          path: base/patch.bps

      - name: Cleanup
        if: always()
        run: rm -rf *.nds

  test-desmume:
    name: Apply base patch and run py-desmume integration tests
    needs: generate-base-patch
    # Windows is used to run the desmume-based tests because py-desmume has issues running on headless ubuntu
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: patch.bps

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Clone Flips repo
        uses: actions/checkout@v3
        with:
          repository: Alcaro/Flips
          path: Flips

      - name: Get latest commit hash from Flips repo
        id: flips-hash
        run: |
          echo "::set-output name=flips_hash::$(git rev-parse --short HEAD)"
        working-directory: Flips

      - name: Cache Flips executable
        uses: actions/cache@v2
        id: flips-cache
        env:
          cache-name: cache-flips
        with:
          path: Flips/*
          key: ${{ env.cache-name }}-${{ steps.flips-hash.outputs.flips_hash }}-${{ runner.os }}

      - name: Compile Flips tool
        if: steps.flips-cache.outputs.cache-hit != 'true'
        run: |
          mingw32-make CFLAGS=-O2
        working-directory: Flips

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Fetch PH rom
        run: |
          pip install gdown
          gdown ${{ secrets.PH_GOOGLE_DRIVE_ID }}

      - name: Patch the rom
        run: |
          ./Flips/flips.exe --apply patch.bps $(ls *.nds) out.nds

      - name: Run tests
        run: |
          pip install tox
          PY_DESMUME_BATTERY_DIR="$pythonLocation" tox -e test
        env:
          PH_ROM_PATH: out.nds

      - name: Cleanup
        if: always()
        run: rm -rf *.nds
  
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the CI tool
        uses: robinraju/release-downloader@v1
        with:
          repository: Ibot02/tmcr-newlogic-ci
          tag: "v1.0"
          filename: "tmcr-newlogic-ci"
          tarBall: false
          zipBall: false

      - name: Make it executable
        run: chmod +x "$GITHUB_WORKSPACE/tmcr-newlogic-ci"

      - name: Run the CI tool
        run: |
          shopt -s globstar
          for file in **/*.logic; do
            ./tmcr-newlogic-ci "$file"
          done;

  test-shuffler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout rando-shuffler repo
        uses: actions/checkout@v3
        with:
          repository: 21aslade/rando-shuffler
          ref: b1100f164d65b7eae517d0bdf2dcaf7f62b70824
          path: rando-shuffler

      - name: Get cache key
        id: shuffler-cache-key
        run: echo "::set-output name=key::$(git rev-parse HEAD)"
        shell: bash
        working-directory: rando-shuffler

      - uses: actions/cache@v3
        id: rando-shuffler-cache
        with:
          path: rando-shuffler
          key: ${{ steps.shuffler-cache-key.outputs.key }}

      - name: Compile rando-shuffler
        if: steps.rando-shuffler-cache.outputs.cache-hit != 'true'
        run: |
          rustup install nightly
          cargo +nightly build
        working-directory: rando-shuffler
        env:
          CARGO_TERM_COLOR: always

      - name: Make it executable
        run: chmod +x rando-shuffler/target/debug/rando_shuffler

      - name: Run the shuffler
        run: |
          shopt -s globstar
          find rando-shuffler/ -name "*.logic" -type f -delete # remove test files
          file_count=0
          failed=0;
          for file in **/*.logic; do
            echo "$file... ";
            status=0
            rando-shuffler/target/debug/rando_shuffler "$file" || status=1
            if [[ $status != 0 ]]; then
              failed=$((failed + 1));
            else
              echo " PASSED";
            fi
            echo "-------------------------------"
            echo ""
            file_count=$((file_count + 1))
          done;
          echo "RESULTS: $((file_count - failed)) / $file_count passed"
          if [[ $failed != 0 ]]; then
            exit 1;
          fi
