name: test
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run Python tests
        run: |
          pip install tox
          tox

  test-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run C tests
        run: |
          DOCKER_BUILDKIT=1 docker build --target lint .
        working-directory:
          base
